### ISSUE TITLE
Redundant UMain elements

### ISSUE THREAD

**Issue by mcfarljw** [nuxt-ui-pro/docs#22]
I noticed that the root `app.vue` and `layouts/docs.vue` files are both referencing the `UMain` element which seems like it might redundantly create nested `main` elements.

https://github.com/nuxt-ui-pro/docs/blob/bfff9ab21b4a0b5072f20944e2cd6e3768815759/app.vue#L34-L38
https://github.com/nuxt-ui-pro/docs/blob/bfff9ab21b4a0b5072f20944e2cd6e3768815759/layouts/docs.vue#L8-L20

**Comment by benjamincanac** [comment]
Indeed, this was a mistake! Thanks for the report 😊
