### ISSUE TITLE
NuxtProDocs - Multiple Docs Content Directories - Issues

### ISSUE THREAD

**Issue by Mat4m0** [nuxt-ui-pro/docs#43]
Hello :wave:,  
I am having issues setting up a Documentation site with multiple "docs" inside.
I setup a repo where everything is already setup to check the issue in more detail:
https://github.com/Mat4m0/fork_nuxt-docs

1) **Important**: I am having the issue when i have a index page in a docs directory, when pressing a sublink it hides itself. (see images)

The code what computes the links to show (from nuxt.com site)
For the main docs:
```ts
const navigationLinks = computed(() => {
  const path = ['/docs', route.params.slug?.[0]].filter(Boolean).join('/')

  return mapContentNavigation(navPageFromPath(path, navigation.value)?.children || [])
})
```
For the docs2
```ts
// ...same
  const path = ['/docs2', route.params.slug?.[0]].filter(Boolean).join('/')
// ...same
```

<img width="1088" alt="image2" src="https://github.com/nuxt-ui-pro/docs/assets/79974907/a9b4fa26-e67b-4c78-b9fe-c5cfcee1d4ae">
<img width="1046" alt="image" src="https://github.com/nuxt-ui-pro/docs/assets/79974907/05bb1d2c-e1cc-4660-a740-db61123b75a6">

2) **Optional**: I just build a whacky solution to keep the link icon active when browsing the subdirectories. A more elegant solution would be appreciated. 

3) **DocsUpdate** : Maybe this workflow could be interesting also for others and can be included in a official Documentation?

Many thanks in advance!! :relaxed:

**Comment by efuo** [comment]
Maybe you can view the official documentation in the way you add a different version of [the documentation](https://ui.nuxt.com/)?The source code can be found in the repository

**Comment by efuo** [comment]
```diff
<template>
  <UMain>
    <UContainer>
      <UPage>
        <template #left>
          <UAside>
+            <BranchSelect />

            <UNavigationTree :links="mapContentNavigation(navigation)" />
          </UAside>
        </template>

        <slot />
      </UPage>
    </UContainer>
  </UMain>
</template>

<script setup lang="ts">
import type { NavItem } from '@nuxt/content/dist/runtime/types'

const nav = inject<Ref<NavItem[]>>('navigation')

const navigation = computed(() => nav.value.filter(item => !item._path.startsWith('/pro')))
</script>
```

this component

**Comment by efuo** [comment]
> ```diff
> <template>
>   <UMain>
>     <UContainer>
>       <UPage>
>         <template #left>
>           <UAside>
> +            <BranchSelect />
> 
>             <UNavigationTree :links="mapContentNavigation(navigation)" />
>           </UAside>
>         </template>
> 
>         <slot />
>       </UPage>
>     </UContainer>
>   </UMain>
> </template>
> 
> <script setup lang="ts">
> import type { NavItem } from '@nuxt/content/dist/runtime/types'
> 
> const nav = inject<Ref<NavItem[]>>('navigation')
> 
> const navigation = computed(() => nav.value.filter(item => !item._path.startsWith('/pro')))
> </script>
> ```
> 
> this component

BranchSelect.vue
```vue
<template>
  <UMain>
    <UContainer>
      <UPage>
        <template #left>
          <UAside>
            <BranchSelect />

            <UNavigationTree :links="mapContentNavigation(navigation)" />
          </UAside>
        </template>

        <slot />
      </UPage>
    </UContainer>
  </UMain>
</template>

<script setup lang="ts">
import type { NavItem } from '@nuxt/content/dist/runtime/types'

const nav = inject<Ref<NavItem[]>>('navigation')

const navigation = computed(() => nav.value.filter(item => !item._path.startsWith('/pro')))
</script>
```

**Comment by Mat4m0** [comment]
Thanks, I already have a solution. 
@benjamincanac how to handle these scenarios? I could an add a page to the [docs folder](https://github.com/nuxt-ui-pro/docs/tree/main/content/1.getting-started)?

**Comment by benjamincanac** [comment]
Not sure it answers your question but for the Nuxt UI docs, we use different sources with `@nuxt/content`: https://github.com/nuxt/ui/blob/dev/docs/nuxt.config.ts#L47 and then compute the navigation based on the route path: https://github.com/nuxt/ui/blob/dev/docs/app.vue#L45.

**Comment by efuo** [comment]
sorry, may have misled

> 谢谢，我已经有解决方案了。 @benjamincanac如何处理这些场景？[我可以向文档文件夹](https://github.com/nuxt-ui-pro/docs/tree/main/content/1.getting-started)添加一个页面吗？

**Comment by efuo** [comment]
> sorry, may have misled

**Comment by efuo** [comment]
> For me the question is if I should setup a _"How to setup a multi docs structure with NuxtUIProDocs"_? Think this could be useful for others in the future.
> 
> Like [Docusaurus ](https://docusaurus.io/docs/docs-multi-instance)

multi-document seen [Content Docs](https://content.nuxt.com)

**Comment by benjamincanac** [comment]
Sorry, but I still don't get your issue. If you encounter a bug, please provide a reproduction.
