### ISSUE TITLE
 Could you please provide a separate deployment document?

### ISSUE THREAD

**Issue by wleelw** [nuxt-ui-pro/docs#46]
I cannot deploy simply by viewing the documentation of Pro, thank you!
Many functions cannot be displayed correctly

**Comment by benjamincanac** [comment]
Not sure to understand your issue here, are you having trouble deploying your Nuxt app to something like Vercel for example?

**Comment by wleelw** [comment]
No, I would like to know the explanation of how to use the content section, such as how to configure index. ml `features`

**Comment by benjamincanac** [comment]
Have you checked the Nuxt UI Pro docs? https://ui.nuxt.com/pro/getting-started

**Comment by wleelw** [comment]
Yes...but I don't quite understand😂

**Comment by wleelw** [comment]
it is too professional

**Comment by wleelw** [comment]
> Are you trying to deploy this from [Nuxt Studio](https://nuxt.studio/)?

No, but I already understand, thank you!
