### ISSUE TITLE
[Help]: how to do this feature?

### ISSUE THREAD

**Issue by everfu** [nuxt-ui-pro/docs#62]
<img width="281" alt="image" src="https://github.com/nuxt-ui-pro/docs/assets/74389842/265be8f9-e213-4264-9a35-27cb6492297d">

How does this switch work?

**Comment by benjamincanac** [comment]
You can have a look at the `nuxt/ui` documentation:

- https://github.com/nuxt/ui/blob/dev/docs/plugins/ui.ts
- https://github.com/nuxt/ui/tree/dev/docs/components/color-picker

**Comment by everfu** [comment]
👌, thk
