### ISSUE TITLE
[Help]: Please explain why this generates index.yml in the sidebar as well

### ISSUE THREAD

**Issue by everfu** [nuxt-ui-pro/docs#63]
1. 
<img width="1529" alt="image" src="https://github.com/nuxt-ui-pro/docs/assets/74389842/2e48db5c-17f2-40d8-b49e-19d817a4a832">
<img width="1826" alt="image" src="https://github.com/nuxt-ui-pro/docs/assets/74389842/8ba49a37-8c46-456d-bbf9-83b48d28e752">
2. repo
https://github.com/everfu/solitude.js.org

**Comment by benjamincanac** [comment]
You should replace `navigation: true` to `navigation: false` if you don't want it in your navigation.

**Comment by everfu** [comment]
> You should replace `navigation: true` to `navigation: false` if you don't want it in your navigation.

👌
