### ISSUE TITLE
UI Pro license for nuxt modules

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-ui-pro/docs#68]
Similar to https://github.com/nuxt-ui-pro/docs/issues/45, I would like to use this module to build documentation for a few nuxt modules. Would it be possible to get a free nuxt-ui pro license for this use case? This helps module maintainers and at the same time is a good promotion for nuxt ui.

This is especially relevant as @Atinux states in https://github.com/nuxt-themes/docus/issues/1016#issuecomment-1866937922 that the currently recommended docus module is no longer actively maintaned and nuxt-ui-pro/docs is one of the recommended alternatives.

**Comment by Atinux** [comment]
Yes it's possible @tobiasdiez 

Send me a message at seb [at] nuxtlabs.com with the module you are building with the GitHub repository.
