### ISSUE TITLE
Package import specifier "#internal/nitro/virtual/plugins" is not defined in package - Cannot run locally via pnpm dev

### ISSUE THREAD

**Issue by gwynhokkers** [nuxt-ui-pro/docs#80]
I'm having an issue running this locally. Maybe I'm missing something. Only rolling back to pre nuxt 3.10 and changing the whole folder structure to v3 seems to do anything.

```
[worker reload] [worker init] Package import specifier "#internal/nitro/virtual/plugins" is not defined in package /Users/gh/Documents/code/nuxt/cookbook/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/package.json imported from /Users/gh/Documents/code/nuxt/cookbook/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/app.mjs
``` 

This is a fresh install cloned directly from the repo.

Package.json
```
{
	"name": "nuxt-ui-pro-template-docs",
	"private": true,
	"type": "module",
	"scripts": {
	  "build": "nuxt build",
	  "dev": "nuxt dev",
	  "generate": "nuxt generate",
	  "preview": "nuxt preview",
	  "postinstall": "nuxt prepare",
	  "lint": "eslint .",
	  "typecheck": "nuxt typecheck"
	},
	"dependencies": {
	  "@iconify-json/heroicons": "^1.1.21",
	  "@iconify-json/simple-icons": "^1.1.109",
	  "@nuxt/content": "^2.13.1",
	  "@nuxt/fonts": "^0.7.1",
	  "@nuxt/image": "^1.7.0",
	  "@nuxt/ui-pro": "^1.3.1",
	  "nuxt": "^3.12.3",
	  "nuxt-og-image": "^3.0.0-rc.64"
	},
	"devDependencies": {
	  "@nuxt/eslint": "^0.3.13",
	  "@nuxthq/studio": "^2.0.3",
	  "eslint": "^9.6.0",
	  "vue-tsc": "^2.0.26"
	}
}
```

Running on an M2 2022 MacBook Air.
Tried on Node: v22.5.1 and v20.16.0 using pnpm v9.6.0

**Comment by benjamincanac** [comment]
Would you mind providing a reproduction?

**Comment by benjamincanac** [comment]
Have you tried with latest `nuxt@3.12.4`?

**Comment by gwynhokkers** [comment]
I just updated to `nuxt@3.12.4` as suggested and I'm still getting the same issue.

I've attempted to include a reproduction on [stackblitz](https://stackblitz.com/~/github.com/gwynhokkers/cookbook?file=nuxt.config.ts) but its actually showing a different, but similar error now.

```
 ERROR  [worker reload] [worker init] Cannot find package '@css-inline/css-inline-wasm' imported from /home/gwynhokkers/cookbook/.nuxt/dev/index.mjs
```

**Comment by benjamincanac** [comment]
It might be because of the `nuxt-og-image` module, can you try removing it to see if it fixes the issue?

**Comment by gwynhokkers** [comment]
Just tried rolling back to node v18 to be on parity with stackblitz but still no bueno.
What version of node and pnpm are you using?

**Comment by benjamincanac** [comment]
Node 20 and PNPM 9.6

**Comment by gwynhokkers** [comment]
Yup - I'm using exactly the same and get the same issue. Tried cloning to a new directory and installing fresh and still same issue. I'm stumped. Could try it on another machine but that wouldn't really solve my issue.

**Comment by gwynhokkers** [comment]
Good news! I have managed to get it working locally - by not using the same directory as my other code files and instead creating a new one outside of where I had some other nuxt 3 projects.
Now why this is possibly causing an issue is beyond me. But at least I can kind of move on with my life. Thanks @benjamincanac for your time.
