### ISSUE TITLE
What does Freemium mean?

### ISSUE THREAD

**Issue by derHodrig** [nuxt-ui-pro/docs#97]
![image](https://github.com/user-attachments/assets/56d33dec-8e28-4faa-b14e-1a4a1687bb4e)

[As we see here, Nuxt Docs is advertised as freemium](https://nuxt.com/templates), freemium means, that there are free elements.
Which are they or better to say, can I use the docs theme free of charge as an upgrade of the old nuxt documentation tool?

**Comment by benjamincanac** [comment]
This template uses Nuxt UI Pro which if free in development, you need a license to build your application. You can learn more about this here: https://ui.nuxt.com/pro/pricing
