### ISSUE TITLE
我想知道这个模板能支持数据从接口中获取吗？

### ISSUE THREAD

**Issue by hth520** [nuxt-ui-pro/docs#98]
我需要对接一个由后台维护的文档，数据在数据库中，通过Java维护的接口拿数据并且渲染在这个项目上

**Comment by benjamincanac** [comment]
English please

**Comment by hth520** [comment]
I need to interface with a document maintained by the background, the data is in the database, and the data is taken and rendered on the project through the interface maintained by Java,Does the project support data fetching from the interface?

**Comment by benjamincanac** [comment]
This template is using `@nuxt/content`: https://content.nuxt.com/ so it's based on Markdown files. You can however update it to fetch from your database instead.
